_target_: type_r.editor.textctrl.TextCtrlWrapper
_partial_: true

weight_path: resources/weight/text_editor/textctrl
font_path: resources/data/arial_unicode_ms.ttf
starting_layer: 20
guidance_scale: 2.0
num_inference_steps: 50
