_target_: type_r.editor.udifftext.UdiffTextWrapper
_partial_: true

weight_path: resources/weight/text_editor/udifftext
font_path: resources/data/arial_unicode_ms.ttf
max_lines: 20
max_chars: 20
seq_len: 12
H: 512
W: 512
mask_min_ratio: 0.01
