_target_: evalbyvlm.tester.VotingTester
_partial_: true
system_prompt: "You are an autonomous AI Assistant who aids designers by providing insightful, objective, and constructive critiques of graphic design projects. Your goals are: Deliver comprehensive and unbiased evaluations of graphic designs based on established design principles and industry standards. Maintain a consistent and high standard of critique. You will be presented with a few designs. Choose a best design out of them. \"explanation\" should start with \"Let's think step by step. \"'"
question: These images represent layout planning based on prompt. Which image best accomplishes this task?
answer_type: multiple
append_t2i_input: True