[project]
name = "type-r-eval"
version = "0.1.0"
description = "Type-R evaluation package."
readme = "README.md"
authors = [
    { name = "Wataru Shimoda", email = "wataru_shimoda@cyberagent.co.jp" },
]
requires-python = ">=3.10, <3.13"
dependencies = [
    "pandas>=2.2.3",
    "pydantic>=2.10.6",
    "datasets>=3.3.2,<3.4.0",
    "vlmeval",
    "type-r-ocr",
    "clip",
    "jsonlines>=4.0.0",
    "scikit-learn>=1.6.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["type_r"]

[tool.uv.sources]
vlmeval = { path = "../VLMEvalKit" }
type-r-ocr = { workspace = true }
clip = { git = "https://github.com/openai/CLIP.git" }
