_target_: type_r.t2i.SD3dot5
_partial_: true

# weight directory path
pretrained_model_name_or_path: stabilityai/stable-diffusion-3.5-large

# cache directory path
cache_dir: resources/weight/t2i/stable-diffusion-3.5-large

# pipeline kwargs
low_cpu_mem_usage: true
offload_state_dict: false

# weight loading options
enable_model_cpu_offload: false
run_on_low_vram_gpus: false

# hyperparams
use_negative_prompts: true
guidance_scale: 4.5
num_inference_steps: 40
seed: null
image_type: square
resolution: 1.0
resolution_type: area
