# output directory path
output_dir: ???

# option for loading word mapping information
load_word_mapping: false

# option for filtering OCR detection results
filter_detection: true

# size rate along a height of an image for filtering OCR detection results
filtering_size_rate: 0.04

# dummy directory for job
job-dir: tmp

# openai config
use_azure: false

# change output directory
# see https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/
hydra:
  run:
    dir: /tmp/hydra/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /tmp/hydra/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

defaults:
  - _self_
  - dataset: marioeval
  - ocr_detection: paddleocr
  - ocr_recognition: modelscope
  - text_eraser: padding
  - adjuster: default
