[project]
name = "type-r-core"
version = "0.1.0"
description = "Type-R core package."
readme = "README.md"
authors = [
    { name = "Wataru Shimoda", email = "wataru_shimoda@cyberagent.co.jp" },
]
requires-python = ">=3.10, <3.13"
dependencies = [
    "numpy>=2.2.3",
    "opencv-python>=4.6.0.66",
    "pydantic>=2.10.6",
    "scikit-image>=0.25.2",
    "simplejson>=3.20.1",
    "sortedcontainers>=2.4.0",
    "torch",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["type_r"]  # src layout does not work in editable mode.
